import type { Product, Review } from './types';

export const reviews: Review[] = [
  {
    id: 'rev1',
    author: 'Sarah J.',
    avatar: 'avatar1',
    rating: 5,
    title: 'Absolutely beautiful!',
    comment: 'The quality of this linen shirt is outstanding. It feels so soft and breathable. I\'ve received so many compliments!',
  },
  {
    id: 'rev2',
    author: 'Michael B.',
    avatar: 'avatar2',
    rating: 4,
    title: 'Great fit and sustainable',
    comment: 'Love that these trousers are made from hemp. They are comfortable and look great for casual or semi-formal occasions. A bit pricey but worth it for the quality.',
  },
  {
    id: 'rev3',
    author: 'Emily K.',
    avatar: 'avatar3',
    rating: 5,
    title: 'My new favorite dress',
    comment: 'This dress is a dream. It\'s so flowy and comfortable, perfect for summer days. The beige color is so versatile. Highly recommend!',
  },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'Eira Linen Shirt',
    slug: 'eira-linen-shirt',
    price: 85.00,
    images: ['product1-1', 'product1-2'],
    category: 'Tops',
    description: 'A timeless button-down shirt made from 100% organic European linen. Breathable, durable, and effortlessly chic.',
    details: [
      '100% GOTS Certified Organic Linen',
      'Mother of pearl buttons',
      'Relaxed fit',
      'Made ethically in Portugal',
    ],
    reviews: [reviews[0]],
  },
  {
    id: 'prod2',
    name: 'Gaia Cotton Dress',
    slug: 'gaia-cotton-dress',
    price: 120.00,
    images: ['product2-1'],
    category: 'Dresses',
    description: 'The perfect summer dress, crafted from lightweight organic cotton. Features a tiered skirt and adjustable straps for a comfortable, flattering fit.',
    details: [
      '100% Organic Cotton Poplin',
      'Adjustable spaghetti straps',
      'Side seam pockets',
      'Fair trade certified',
    ],
    reviews: [reviews[2]],
  },
  {
    id: 'prod3',
    name: 'Atlas Wool Sweater',
    slug: 'atlas-wool-sweater',
    price: 150.00,
    images: ['product3-1'],
    category: 'Knitwear',
    description: 'Stay cozy in our Atlas sweater, knitted from responsibly sourced RWS certified wool. A chunky, oversized fit for ultimate comfort.',
    details: [
      '100% RWS Certified Merino Wool',
      'Chunky fisherman rib stitch',
      'Oversized, comfortable fit',
      'Naturally temperature-regulating',
    ],
    reviews: [],
  },
  {
    id: 'prod4',
    name: 'Orion Hemp Trousers',
    slug: 'orion-hemp-trousers',
    price: 110.00,
    images: ['product4-1'],
    category: 'Bottoms',
    description: 'Versatile and durable trousers made from a blend of hemp and organic cotton. Straight-leg cut with a slightly cropped ankle.',
    details: [
      '55% Hemp, 45% Organic Cotton',
      'High-waisted, straight-leg fit',
      'Durable and gets softer with wash',
      'Dyed with non-toxic, low-impact dyes',
    ],
    reviews: [reviews[1]],
  },
    {
    id: 'prod5',
    name: 'Sol Organic Tee',
    slug: 'sol-organic-tee',
    price: 45.00,
    images: ['product5-1'],
    category: 'Tops',
    description: 'The perfect everyday t-shirt. Made from luxuriously soft 100% organic Pima cotton, it\'s a wardrobe staple you\'ll reach for again and again.',
    details: [
      '100% GOTS Certified Organic Pima Cotton',
      'Classic crewneck fit',
      'Soft, durable, and pill-resistant',
      'Made in a carbon-neutral factory',
    ],
    reviews: [],
  },
  {
    id: 'prod6',
    name: 'Nyx Recycled Jacket',
    slug: 'nyx-recycled-jacket',
    price: 195.00,
    images: ['product6-1'],
    category: 'Outerwear',
    description: 'A sleek, water-resistant jacket made from 100% recycled materials. Lightweight yet warm, it\'s perfect for transitional weather.',
    details: [
      '100% Recycled Polyester shell and lining',
      'PFC-free water-resistant coating',
      'Insulated with recycled materials',
      'Packs into its own pocket',
    ],
    reviews: [],
  },
];
